### ISSUE TITLE
error: possibly undefined macro: AC_MSG_ERROR at unifyfs configure

### ISSUE THREAD

**Issue by Mosseridan** [LLNL/UnifyFS#410]
### System information

Type                   | Version/Name
---                    |     ---
Operating System       | Centos 7
OS Version             | Linux 3.10.0-327.22.2.el7.x86_64
Architecture           | x86-64
UnifyFS Version        | 0.9.0

### Describe the problem you're observing
Hello. I keep getting the following error while running unifyfs start -S /home/[my username]/unify_test_dir

```
srun: error: node018: task 1: Illegal instruction
srun: error: node017: task 0: Illegal instruction
```

I can't find any log files or any information about what instruction it was.

Your help is very much appreciated as i am looking forward to try UnifyFS.
Thank you.

**Comment by MichaelBrim** [comment]
@Mosseridan Typically, illegal instruction errors happen when the binary is run on an incompatible architecture from where it was compiled. Are you using the same system to build and run?

From the srun error messages, it appears it is the unifyfsd binary that is generating the error. It is probably failing right away, which is why no logs or additional information are generated.

**Comment by Mosseridan** [comment]
@MichaelBrim Thank you for your response. Yes I did build and run using the same system. is there any way a could extract any additional information? Or are there any suggestions on how to rebuild UnifyFS?

**Comment by MichaelBrim** [comment]
@Mosseridan Did you build UnifyFS from source (e.g., using the bootstrap script), or did you use spack?

**Comment by scientific-computing-nrcn** [comment]
spack (I am collaborating with Idan)

**Comment by galoren** [comment]
spack (I am collaborating with Idan)

**Comment by Mosseridan** [comment]
Hi. OK so i found out that one of the nodes I tried to run on did have a slightly different architecture (both intel). I am now trying to reinstall UnifyFS devel brabch (which is the spack default) with spack with gcc8.1.0 and target architecture x86_64 which should be compatible with both nodes. 

The installation command I used is:
`spack install unifyfs+hdf5+fortran%gcc@8.1.0 target=x86_64`

While installing with spack I get the following error at the 'configure' phase of the unifyfs installation:
```
==> Installing unifyfs
==> Searching for binary cache of unifyfs
==> Warning: No Spack mirrors are currently configured
==> No binary for unifyfs found: installing from source
==> Cloning git repository: https://github.com/LLNL/UnifyFS.git on branch dev
==> No checksum needed when fetching with git
==> Already staged spack-stage-unifyfs-develop-huqsvnfcvdkhepmltppbk33hswch4jkv in /tmp/root/spack-stage/spack-stage-unifyfs-develop-huqsvnfcvdkhepmltppbk33hswch4jkv
==> No patches needed for unifyfs
==> Building unifyfs [AutotoolsPackage]
==> Executing phase: 'autoreconf'
==> Executing phase: 'configure'
==> Error: ProcessError: Command exited with status 1:
    '/tmp/root/spack-stage/spack-stage-unifyfs-develop-huqsvnfcvdkhepmltppbk33hswch4jkv/spack-src/configure' '--prefix=/opt/sw/spack/0.13.0/opt/spack/linux-centos7-x86_64/gcc-8.1.0/unifyfs-develop-huqsvnfcvdkhepmltppbk33hswch4jkv' '--without-numa' '--with-hdf5=/opt/sw/spack/0.13.0/opt/spack/linux-centos7-x86_64/gcc-8.1.0/hdf5-1.10.5-rwhvvkwo5vdfjey2vqqigcdi7iai52cz/bin/h5pcc' '--enable-fortran' '--enable-silent-rules'

2 errors found in build log:
     17    libtoolize: copying file 'm4/ltoptions.m4'
     18    libtoolize: copying file 'm4/ltsugar.m4'
     19    libtoolize: copying file 'm4/ltversion.m4'
     20    libtoolize: copying file 'm4/lt~obsolete.m4'
     21    libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
     22    autoreconf: running: /opt/sw/spack/0.13.0/opt/spack/linux-centos7-x86_64/gcc-8.1.0/autoconf-2.69-i74vge24l5ce4ew36i4px3cjz2y7lojp/bin/autoconf --force
  >> 23    configure.ac:144: error: possibly undefined macro: AC_MSG_ERROR
     24          If this token and others are legitimate, please use m4_pattern_allow.
     25          See the Autoconf documentation.
     26    autoreconf: /opt/sw/spack/0.13.0/opt/spack/linux-centos7-x86_64/gcc-8.1.0/autoconf-2.69-i74vge24l5ce4ew36i4px3cjz2y7lojp/bin/autoconf failed with exit status: 1
     27    
     28    Please proceed with configuring, compiling, and installing.
     29    ==> Executing phase: 'configure'
     30    ==> [2020-02-05-13:40:15.428052] '/tmp/root/spack-stage/spack-stage-unifyfs-develop-huqsvnfcvdkhepmltppbk33hswch4jkv/spack-src/configure' '--prefix=/opt/sw/spack
           /0.13.0/opt/spack/linux-centos7-x86_64/gcc-8.1.0/unifyfs-develop-huqsvnfcvdkhepmltppbk33hswch4jkv' '--without-numa' '--with-hdf5=/opt/sw/spack/0.13.0/opt/spack/l
           inux-centos7-x86_64/gcc-8.1.0/hdf5-1.10.5-rwhvvkwo5vdfjey2vqqigcdi7iai52cz/bin/h5pcc' '--enable-fortran' '--enable-silent-rules'
     31    configure: WARNING: unrecognized options: --without-numa
  >> 32    configure: error: cannot find install-sh, install.sh, or shtool in "/tmp/root/spack-stage/spack-stage-unifyfs-develop-huqsvnfcvdkhepmltppbk33hswch4jkv/spack-src"
            "/tmp/root/spack-stage/spack-stage-unifyfs-develop-huqsvnfcvdkhepmltppbk33hswch4jkv/spack-src/.." "/tmp/root/spack-stage/spack-stage-unifyfs-develop-huqsvnfcvdk
           hepmltppbk33hswch4jkv/spack-src/../.."

See build log for details:
  /tmp/root/spack-stage/spack-stage-unifyfs-develop-huqsvnfcvdkhepmltppbk33hswch4jkv/spack-build-out.txt

```
And here are the contents of the build log:

```
==> Executing phase: 'autoreconf'
==> [2020-02-05-13:40:02.787055] '/bin/bash' './autogen.sh'

... UnifyFS autogen ...

Running libtoolize...
Running autoreconf...
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force 
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
autoreconf: running: /opt/sw/spack/0.13.0/opt/spack/linux-centos7-x86_64/gcc-8.1.0/autoconf-2.69-i74vge24l5ce4ew36i4px3cjz2y7lojp/bin/autoconf --force
configure.ac:144: error: possibly undefined macro: AC_MSG_ERROR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /opt/sw/spack/0.13.0/opt/spack/linux-centos7-x86_64/gcc-8.1.0/autoconf-2.69-i74vge24l5ce4ew36i4px3cjz2y7lojp/bin/autoconf failed with exit status: 1

Please proceed with configuring, compiling, and installing.
==> Executing phase: 'configure'
==> [2020-02-05-13:40:15.428052] '/tmp/root/spack-stage/spack-stage-unifyfs-develop-huqsvnfcvdkhepmltppbk33hswch4jkv/spack-src/configure' '--prefix=/opt/sw/spack/0.13.0/opt/spack/linux-centos7-x86_64/gcc-8.1.0/unifyfs-develop-huqsvnfcvdkhepmltppbk33hswch4jkv' '--without-numa' '--with-hdf5=/opt/sw/spack/0.13.0/opt/spack/linux-centos7-x86_64/gcc-8.1.0/hdf5-1.10.5-rwhvvkwo5vdfjey2vqqigcdi7iai52cz/bin/h5pcc' '--enable-fortran' '--enable-silent-rules'
configure: WARNING: unrecognized options: --without-numa
configure: error: cannot find install-sh, install.sh, or shtool in "/tmp/root/spack-stage/spack-stage-unifyfs-develop-huqsvnfcvdkhepmltppbk33hswch4jkv/spack-src" "/tmp/root/spack-stage/spack-stage-unifyfs-develop-huqsvnfcvdkhepmltppbk33hswch4jkv/spack-src/.." "/tmp/root/spack-stage/spack-stage-unifyfs-develop-huqsvnfcvdkhepmltppbk33hswch4jkv/spack-src/../.."
```

I also tried to install UnifyFS version 0.9.0 but here spack is not able to fetch the installation files

```
==> Installing unifyfs
==> Searching for binary cache of unifyfs
==> Warning: No Spack mirrors are currently configured
==> No binary for unifyfs found: installing from source
==> Warning: There is no checksum on file to fetch unifyfs@0.9.0 safely.
==>   Fetch anyway? [y/N] y
==> Fetching with no checksum.
  Add a checksum or use --no-checksum to skip this check.
==> Fetching https://github.com/LLNL/UnifyFS/releases/download/v0.9.0/unifycr-0.9.0.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
==> Fetching from https://github.com/LLNL/UnifyFS/releases/download/v0.9.0/unifycr-0.9.0.tar.gz failed.
==> Error: FetchError: All fetchers failed for spack-stage-unifyfs-0.9.0-ecxtfifriu6ikoubxjvzb6tkudvkzusn

/opt/sw/spack/0.13.0/lib/spack/spack/package.py:1079, in do_fetch:
       1076                raise FetchError("Will not fetch %s" %
       1077                                 self.spec.format('{name}{@version}'), ck_msg)
       1078
  >>   1079        self.stage.create()
       1080        self.stage.fetch(mirror_only)
       1081        self._fetch_time = time.time() - start_time
       1082
```

As always, your help is very much appreciated.

**Comment by MichaelBrim** [comment]
@Mosseridan We recently removed the --with-numa configure option, and I don't think the corresponding spack package update has been upstreamed yet (@CamStan can you confirm?). I'm not sure it will resolve your spack build problem, but editing your local package for unifyfs to remove the '--without-numa' might help.

**Comment by Mosseridan** [comment]
Hi @MichaelBrim. We I did not use the --with-numa configure option in my installation. From what i can tell, the problem lies in the usage of AC_MSG_ERROR in the the configure.ac file whilst the usage of m4 is commented out at line 5 of Makefile.am.

I tried to install Unifyfs version 0.2.0 with spack and the same flags and it did succeed as it dose not use AC_MSG_ERROR in its configure.ac.

can you confirm my supposition?

Thanks again.

**Comment by CamStan** [comment]
@Mosseridan, there are a couple of things happening here:

First, variants when installing a Spack package have default values (true or false) which can be seen with the command `spack info unifyfs`. So when you include `+fortran`, you're setting this variant to true. However, for any variant you don't provide, Spack will autofill with the default. So when you type
```
spack install unifyfs+hdf5+fortran
```
what Spack will actually do is
```
spack install unifyfs+hdf5+fortran~numa~pmi~pmix~pmpi
```
Then when the `~numa` variant is set, this corresponds to and in turn sets the `--without-numa` config option.

@MichaelBrim is correct in that we recently removed the `--with-numa` and `--without-numa` configure options, but this change hasn't been upstreamed to Spack yet. This is on me and I will get this change submitted very soon.

As Mike also suggested, if you need this to work right away, you can edit your unifyfs spack package using the command `spack edit unifyfs` and remove the `variant('numa'...` line near the top as well as the `args.extend(self.with_or_without('numa', ...` line near the bottom and this should then work for you locally. 
I'll be fixing this and changing a couple more things with our package as well though, to include renaming the  `pmpi` variant and defaulting it to true, and changing the default install to the latest version (so then to get the develop branch, you'll need to do `spack install unifyfs@develop`. I'll tag you here when these changes have been made, which leads to the second thing.

Second, Spack is constantly being updated (often by the minute) and they don't push these changes to their master branch very often. We have stopped supporting the 0.2.0 version of UnifyFS, but since you're still seeing this and not seeing the 0.9.0 version, I'm assuming your local clone of Spack is out-of-date.
Most likely, you're either using the the master branch of Spack, or if you're using the develop branch, that you simply need to pull the latest changes. So first, if you're not already, I'd recommend making sure your local clone of Spack is using their develop branch and then, because of these constant updates, simply make sure you pull the latest changes from their remote repo (something like `git checkout develop` and `git pull origin develop`).
After doing this, `spack info unifyfs` should show the develop and 0.9.0 versions as being available.

To answer your last question, version 0.2.0 of UnifyFS **does** use the AC_MSG_ERROR, but it recognizes the `--without-numa` option that Spack automatically passes to it since it is still in the source code in that version. It was our very recent removal of the entire numa config option that broke our Spack package and I need to fix that. I will also test with any Intel architecture I have access to and try to get things working as we'd like to work with those as well (although if you need fortran support, we currently only have things working with gfortran, and have some issues open for the the other compilers).

Hopefully this clears things up a bit, but please ask for any clarification if anything I said doesn't make sense.

**Comment by Mosseridan** [comment]
Hi @CamStan. Thank you very much for your detailed reply. I'll update my spack more frequently and will probably wait for the fixed package. Looking forward to trying unifyfs. Yhanks again for your help. Have a great weekend :)

**Comment by MichaelBrim** [comment]
@Mosseridan I reproduced your issue when building from source (not using spack). I think the primary problem is that the uses of `AC_MSG_ERROR` are quoted in configure.ac. When I removed the extra brackets from the uses, autogen.sh and configure did not complain anymore. I'm going to test this a bit more and submit a PR to fix it.

Here's the diff:
```
> git diff configure.ac
diff --git a/configure.ac b/configure.ac
index 9bcb9b1..2ffdd8c 100755
--- a/configure.ac
+++ b/configure.ac
@@ -140,9 +140,10 @@ AS_IF([test "x$enable_fortran" = "xyes"],[
     AC_LANG_POP
 ],[])

-AS_IF([test "$have_C_mpi" != "yes"],[
-    AC_MSG_ERROR(["Couldn't find MPI"])
-],[])
+AS_IF([test "$have_C_mpi" != "yes"],
+    AC_MSG_ERROR(["Couldn't find MPI"]),
+    []
+)

 # look for leveldb library, sets LEVELDB_CFLAGS/LDFLAGS/LIBS
 UNIFYFS_AC_LEVELDB
@@ -195,7 +196,7 @@ AX_LIB_HDF5
 AM_CONDITIONAL([HAVE_HDF5], [test x$with_hdf5 = xyes])

 # Look for pthreads
-AX_PTHREAD([],[AC_MSG_ERROR([pthreads are required])])
+AX_PTHREAD([],AC_MSG_ERROR([pthreads are required]))
```

**Comment by Mosseridan** [comment]
Hi @CamStan  and @MichaelBrim. I updated spack and tried removing the numa configure option from my local spack as @CamStan suggested above . Removing the numa option did not do the trick. Is there a way to tell spack to install unifyfs from @MichaelBrims new fixed branch or should I just wait for you to merge it in to the develop branch?

**Comment by Mosseridan** [comment]
Hi @MichaelBrim  and @CamStan. @MichaelBrims fix worked!
thanks!
