### ISSUE TITLE
Server fails to start with Mercury v2.0.0

### ISSUE THREAD

**Issue by CamStan** [LLNL/UnifyFS#573]
### Describe the problem you're observing

Travis CI was set up to build with the default version of Margo, Mercury, and Argobots.
Mercury has pushed a new default version, v2.0.0.
Recent Travis units tests started failing when using this version as the UnifyFS server was failing to start or stay running.
```
==> Installing mercury-2.0.0-zz3duk7kgdgcr4kbctva5wc5i5zhcyfj
```

### Describe how to reproduce the problem

Build UnifyFS using Margo with Mercury v2.0.0 and run the units tests.

### Include any warning or errors or releveant debugging data

Output from unit tests when attempting to start unifyfs server.
```
2020-11-18T15:09:06 tid=10596 @ process_servers_hostfile() [server/src/unifyfs_server.c:244] found myself at hostfile index=0, pmi_rank=0
2020-11-18T15:09:06 tid=10596 @ main() [server/src/unifyfs_server.c:362] initializing rpc service
2020-11-18T15:09:07 tid=10596 @ setup_local_target() [server/src/margo_server.c:191] margo_init(na+sm://)
2020-11-18T15:09:07 tid=10596 @ setup_remote_target() [server/src/margo_server.c:90] margo RPC server: bmi+tcp://10.20.1.10:44657
2020-11-18T15:09:07 tid=10596 @ rpc_publish_remote_server_addr() [common/src/unifyfs_rpc_util.c:49] publishing server-server rpc address 'bmi+tcp://10.20.1.10:44657'
2020-11-18T15:09:07 tid=10596 @ main() [server/src/unifyfs_server.c:368] "Mercury/Argobots operation error"
1..1
not ok 1 - unifyfsd running
FAIL: 0001-setup.t 1 - unifyfsd running
ERROR: 0001-setup.t - exited with status 1
```

### Current workaround

Use Mercury v1.0.1

**Comment by CamStan** [comment]
Not mentioned above, but the default version of Margo in Spack here is v0.4.3, which is then set up to depend on the the default version of Mercury, which is now v2.0.0.

@carns or @chuckatkins, are you aware of any compatibility changes with Margo v0.4.3 and Mercury v2.0.0 that would prevent these from working together?

**Comment by carns** [comment]
I'm not sure off the top of my head.  We are currently at version 0.9 of margo (tracked in an external repo with the package name "mochi-margo" rather than "margo": https://xgitlab.cels.anl.gov/sds/sds-repo/-/blob/master/packages/mochi-margo/package.py).  We have not tested 0.4.3 recently.

The easiest short term fix might be to have margo 0.4.3 in spack's built-in repo depend on Mercury 1.0.1 (or whatever the last working combination is there)?

In the slightly longer term, we'd like to help coordinate pushing our updated package spec to upstream in spack (and bringing it inline with our preferred naming convention) so that it's easier to stay in sync.

**Comment by carns** [comment]
Here is spack fork/branch that replaces the margo package with our updated mochi-margo (which is heavily tested with Mercury 2.0.0).  I also updated the unifyfs package in this branch to depend on mochi-margo, though the old name will still also work by way of a stub package.

I cannot build unifyfs for some reason (apparently unrelated to margo or mercury) though, so I can't tell if this works.

Do you want to try this out before we open a PR on the spack repo?

**Comment by CamStan** [comment]
Thank you for the update!

Yes, I'll grab your spack fork/branch, try it out, and let you know before opening a PR. We're pushing a new version soon so our spack package will need some updates and dig into why it's failing to build.

**Comment by carns** [comment]
Thanks @CamStan, let me know how it goes.  It looks like I forgot to actually paste the link in the above comment, I just edited it.

**Comment by CamStan** [comment]
@carns, I was able to get this to build, so thank you!

Initially was getting an error when trying to install or do `spack spec unifyfs` :
```
==> Error: No module named 'spack.pkg.mochi'
```
but after changing 
```
from spack.pkg.mochi.mochi_margo import MochiMargo
```
in the `margo` package to
```
from spack.pkg.builtin.mochi_margo import MochiMargo
```
it was able to build.

---

When you do put in a PR to Spack, don't worry about updating the `unifyfs` package as we'll be updating other things in it soon as well.

Lastly, we're not able to run `unifyfs` with these latest version (haven't dug into this yet), but there were some API changes in margo between v0.4.3 and v0.9, correct?
I'll create a separate issue on this so we can be sure to update soon, but for now we'll set our package use margo v0.4.3 (or mochi-margo v0.4.3) and mercury v1.0.1 for our current versions until we can test more with a newer versions.

Granted, I suppose this also means there isn't an urgency for you to upstream your spack package 😅 as we can always test with the `sds-repo` when we're ready to use the later versions.

**Comment by carns** [comment]
Good catch re: the builtin repo path!

So that PR to spack (modulo the repo path fix, minus the unify spackage changes) would be Ok from your perspective, and you'll just restrict the margo/mercury versions in the short term regardless, right?

Please do reach out when you are ready to look at updating to a newer Margo and I'll be happy to help.  The API changes are very minor but I'm not sure which ones you might bump into.  There are some nice internal improvements in Margo to look forward to once you do, though, including some performance improvements (in conjunction with the newer Mercury especially), ability to profile RPCs, ability to set/inspect configuration via json, and some other odds and ends.

**Comment by adammoody** [comment]
Yes, we should make an effort soon to bump to the latest releases of the Mochi stack.  @CamStan , let's bring this up with the group after we stamp this upcoming release of UnifyFS we're trying to get out the door.  It'll be better for us to be on newer software now that we're trying to scale up and debug performance issues and deadlocks that we may get stuck on.

**Comment by CamStan** [comment]
> So that PR to spack (modulo the repo path fix, minus the unify spackage changes) would be Ok from your perspective, and you'll just restrict the margo/mercury versions in the short term regardless, right?

@carns, yes, that is correct. We'll be in touch and we move forward with updating.

@adammoody, agreed on bumping to the latest releases of the Mochi stack. Opened relevant issue #584 to track that and closing this one.
